import { Video } from "../utils/youtubeUtils";
export const ourWorkVideos: Video[] = [
  {
    url: "https://www.youtube.com/watch?v=lW7nBgHv6k4",
    title: "Online Fraud With Me - AstroTalk !",
    description: "In this video i talked about A Fraud Alert with My Experience. This video is for information only ",
    dateUploaded: "24/04/2024",
    views: "415K+",
  },
  {
    url: "https://www.youtube.com/watch?v=_WXHSBxjTv0",
    title: "Shame on You Flipkart - Problem !",
    description: `In this video i talked about Flipkart New Order and Order cancel problem Many times users facing problem with Flipkart like Flipkart Open Box iPhone delivery Flipkart Exchange policy Flipkart Return Policy`,
    dateUploaded: "27/03/2023",
    views: "2.5M+",
  },
  {
    url: "https://www.youtube.com/watch?v=th8qpZuk4bs",
    title: "Don't Follow this - Dark Reality !",
    description: "In this video i talked about some apps which is not good for everyone",
    dateUploaded: "11/09/2022",
    views: "931K+",
  },
  {
    url: "https://www.youtube.com/watch?v=GIzwXjvtRjI",
    title: "This Made in INDIA Mobile Scam Should STOP !",
    description: "This video is very important for you because this mobile smartphone is a type of Scam in online as well as offline market and you should know about this.",
    dateUploaded: "8/05/2021",
    views: "2.2M+",
  },
  {
    url: "https://www.youtube.com/watch?v=9XdWwRWLZME",
    title: "This was - Biggest Smartphone SCAM in India !",
    description: "This was the Biggest smartphone SCAM in India with the name of worlds cheapest mobile",
    dateUploaded: "24/09/2022",
    views: "1.1M+",
  },
  {
    url: "https://www.youtube.com/watch?v=f8RVngngps0",
    title: "This SCAM is Very Serious - Must Watch !",
    description: "This SCAM or Fraud is Very Serious",
    dateUploaded: "10/10/2022",
    views: "2.0M+",
  },
  {
    url: "https://www.youtube.com/watch?v=_39q1Q1yPTQ",
    title: "We Are in Trap - Be Careful !",
    description: "In this Video i talked about how these Betting Companies are trying to push you to use their App and Get in to Trap of this Business. I hope this video brings awareness to new People and this video is for information only and not to defame any Brand",
    dateUploaded: "18/03/2024",
    views: "590K+",
  },
  {
    url: "https://www.youtube.com/watch?v=tO6PqfCJpuY",
    title: "Don't Buy This SCAM via Amazon/Flipkart 😡",
    description: `I bought this mobile smartphone via Flipkart. This budget smartphone comes with 8GB RAM and 256GB Storage, I tested and found you should not buy these type of smartphones because they do not provide value for your money.`,
    dateUploaded: "16/12/2021",
    views: "2.2M+",
  },
  {
    url: "https://www.youtube.com/watch?v=77yeaEFz_94",
    title: "Flipkart Cheated me - Delivery Fraud !",
    description: `In this video I talked about Flipkart service and how I cheated by flipkart shopping You should know about this Flipkart Fraud`,
    dateUploaded: "3/09/2023",
    views: "1.7M+",
  },
  {
    url: "https://www.youtube.com/watch?v=-OrY5Dxs3VA",
    title: "A Big Mistake by This Boy & Mother - STOP !",
    description: `Yaha maine apna opinion diya hai ek young boy ke iPhone buy karke jo usek budget se bahar tha `,
    dateUploaded: "24/07/2024",
    views: "2.4M+",
  },
  {
    url: "https://www.youtube.com/watch?v=aMej6xZIWR8",
    title: "A Big SCAM With You - 500 Cr. Rupees in India !",
    description: `This video is for information and awareness for social media You should watch and follow social media buy carefully`,
    dateUploaded: "8/10/2024",
    views: "860K+",
  },
  {
    url: "https://www.youtube.com/watch?v=OE6hxymoFXY",
    title: "Dear Students - Social Media Life Ki Reality",
    description: `Is video me maine social media par dikhne wale life vs real life ke bare me @GyanTherapy ne apna opinion diya hai. Ye video students ke liye hai jo social media ko bahar se dekh se kuch aur maan lete hai aur umeed hai ye video unke liye helpful rahega.`,
    dateUploaded: "6/12/2021",
    views: "382K+",
  },
];
